---
env:
  browser: true
  es6: true
extends:
- eslint:recommended
- plugin:react/recommended
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
- react
rules:
  array-bracket-spacing:
  - error
  - always
  - singleValue: false
    objectsInArrays: false
  block-spacing:
  - error
  brace-style:
  - error
  - 1tbs
  comma-spacing:
    - error
    - before: false
      after: true
  comma-dangle:
  - error
  - always-multiline
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      align: value
  keyword-spacing:
  - error
  - after: true
    before: true
  eol-last:
  - error
  - unix
  func-call-spacing:
  - error
  space-before-function-paren:
  - error
  - never
  space-in-parens:
  - warn
  - always
  # - exceptions:
  #   - "{}"
  #   - "[]"
  indent:
  - error
  - tab
  no-mixed-spaces-and-tabs:
  - error
  - smart-tabs
  linebreak-style:
  - error
  - unix
  no-whitespace-before-property:
  - error
  quotes:
  - error
  - single
  semi:
  - error
  - never
  semi-spacing:
  - error
  - before: false
    after: true
  space-unary-ops:
  - error
  - words: true
    nonwords: true
    overrides:
      ++: false
      --: false
  no-multiple-empty-lines:
  - error
  - max: 1
  object-curly-newline:
  - error
  - multiline: true
  object-curly-spacing:
  - error
  - always
  - objectsInObjects: false
  arrow-parens:
  - error
  - as-needed
  arrow-spacing:
  - error
  - before: true
    after: true
  react/jsx-curly-spacing:
  - error
  - always
  - spacing:
      objectLiterals: never
  yoda:
  - error
  - never
  no-console:
  - warn
